sonar.projectKey=inventory-app-stage
sonar.projectName=YKG
sonar.sourceEncoding=UTF-8

sonar.sources=server.ts,src/client,src/server,test

sonar.exclusions=**/node_modules/**,**/dist/**,**/reports/**,**/coverage/**,**/*.css,**/*.sql,**/*.d.ts,src/client/public/**

